package com.simplycmd.featherlib.registry;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * @param modId your mod's mod id
 * @param debug optional value, if true dumps autogenerated resources to the run folder, in case you need to override something.
 * @param devOnly optional value, whether or not the content in your registry is only registered in the dev environment
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface Registry {
    String modId();
    boolean debug() default false;
    boolean devOnly() default false;
}
